### PR TITLE
D3 based DialWidget

### PR DESCRIPTION
**Pull request by MignonBelongie**
ready for feedback

### CODE REVIEW

**Comment by davidpablocohn** [comment]
Sorry for the delay on this! Codewise, via inspection and trial, it all
looks good, and you keep teaching me more about JS - I had to look up the
"..." operator, and wish I'd known about that ages ago.

Dial looks great, and almost ready to go. I could imagine a few more
options prior to integration, the main one being an option of whether to
show the numeric value(s) in the center of the gauge, and perhaps whether
to also include the name along with the numeric value. Other than that, it
looks fabulous.

On the timeline, I think the main features I'd like to see are a few more
widget options:
 - min, max  - optional limits on max min display values
 - minRange - minimum difference between max and min

Again, this all looks great - many thanks for taking it on!

**Comment by MignonBelongie** [comment]
I added options 'showNumericValues' and 'showDescriptions'. I'm a little concerned that if both are false, there is no way to see the descriptions. I don't know if you noticed, but there were tooltips on the numeric values (and they're still there if showNumericValues is true and showDescriptions is false). I tried putting tooltips on the pointers, but I just couldn't get it to work right.
One thought is to have a "more info" button that would show the list of fields, and maybe even allow deselecting fields. New feature request, maybe?
Finally, I set the defaults to match the original behavior, but feel free to change them (or any of the other defaults I pulled out of a hat).

**Comment by davidpablocohn** [comment]
I'd missed the tool tips - thanks!

In terms of omitting descriptions, I think lots of times folks will want
the descriptions to be external to the widget, e.g. as a separate text
widget. So I think that's actually a feature rather than a bug.

I think it looks ready to merge with dev as a first pass, if you're happy
with it.  Let me know?

Thanks, too, for opening the "additional features" issue report.

**Comment by MignonBelongie** [comment]
If you're OK with the defaults, go ahead and merge.

**Pull request merged**
